### ISSUE TITLE
localsAsTemplateData doesn't work when caching is enabled

### ISSUE THREAD

**Issue by dpolivy** [donpark/hbs#101]
The new `localsAsTemplateData` function doesn't pass the locals as `data` when the template is already cached.

This line is executed when the template is cached; it needs to be updated to pass in the `data` object:
https://github.com/donpark/hbs/blob/master/lib/hbs.js#L46

On a side note, why is the object duplicated as `__hbsLocals` -- why not just set a flag to indicate the locals should be passed as data, too?

**Comment by defunctzombie** [comment]
could you ping the person that implemented those changes? git blame should help identify who did that

**Comment by dpolivy** [comment]
Will do -- just commented on the original PR. I'm also working on a PR to fix this issue and try to clean up the handling a little bit.

**Comment by defunctzombie** [comment]
:+1:
