### ISSUE TITLE
the separator error under windows... 

### ISSUE THREAD

**Issue by qtisan** [donpark/hbs#109]
i do not know why the replace run error!
while i place the `goodsItem.hbs` in `partials/wechat/listItem/goodsItem.hbs` and i take it with `{{>wechat/listItem/goodsItem}}`, it goes error!
while i place the` goodsItem.hbs` in `partials/wehcat/goodsItem.hbs` and i take it with `{{>wechat/goodsItem}}`, it makes all right!

i saw the `templateName` in runtime result the value `wechat/listItem\goodsItem`, the separator `\\` is not been replaced! and then i test failed at console try.

see the capture, my friend....

thank for help...
![324234](https://cloud.githubusercontent.com/assets/8434908/9838673/b73db452-5a95-11e5-9f43-91bc57a7e428.png)
![12312313](https://cloud.githubusercontent.com/assets/8434908/9838674/b743f3e4-5a95-11e5-9700-56bd3c1f7981.png)

**Comment by qtisan** [comment]
i am sorry for my poor english...

**Comment by qtisan** [comment]
should the `replace('\\', '/')` be `replace(/\\/g, '/')` ?

**Comment by riyadhalnur** [comment]
the replace regex you're using is fine. i think you're problem is filenames. you're using al lowercase when saving the file but referencing them in code in camel case

**Comment by defunctzombie** [comment]
Closing unless this is shown to be a regex issue versus a case issue.
