### ISSUE TITLE
Can't cache layouts

### ISSUE THREAD

**Issue by sn1ckers** [donpark/hbs#114]
Hi

Im having problems to cache layout in the function cacheAndCompile the layout_filename always returns a empty array, it is consumed in tryReadFileAndCache when the array is iterated with shift(). A simple solution is to pass the filename to the function instead from tryReadFileAndCache.

**Comment by defunctzombie** [comment]
need a failing example or test please

**Comment by sn1ckers** [comment]
An example is when I use hbs with a layout, Im rendering myView.hbs and are using layout.hbs as layout and I set locals.cache = true. Then myView.hbs is then cached fine but when it reads and compile my layout.hbs it will never be cached. This is becouse it is defined in this variable **layout_filename**.

  var view_dirs = options.settings.views;

  var **layout_filename** = [].concat(view_dirs).map(function (view_dir) {
    var view_path = path.join(view_dir, layout || 'layout');

    if (!path.extname(view_path)) {
      view_path += extension;
    }

    return view_path;
  });

Which will be a array with my path to layout.hbs and in the function tryReadFileAndCache it is used
with shift(). 

function tryReadFileAndCache(templates) {
    var template = templates.shift();
...
}
tryReadFileAndCache(layout_filename);

So when the function cacheAndCompile is called it uses layout_filename which then is an empty array.

if (options.cache) {
      cache[layout_filename] = layout_template;
    }

So Im bound to always read from disk when Im getting my layout.hbs.

I will try to make a pull request with a solution.

**Comment by sn1ckers** [comment]
When will there be a new release on npm with the fix?

**Comment by defunctzombie** [comment]
published as v4
