### ISSUE TITLE
Exposing locals as template data

### ISSUE THREAD

**Issue by alfgaar** [donpark/hbs#96]
I only use locals to set data used across all pages such as company info and menu items.
I did as you said on the topic 'Exposing locals as template data', but the data is not available for the layout not the partials. According to what is written it shoulld be available to all contexts.

**Comment by umayr-shahid-10p** [comment]
+1. Facing the very same issue.

**Comment by umayr** [comment]
+1. Facing the very same issue.

**Comment by defunctzombie** [comment]
Seems the question was answered.
