### ISSUE TITLE
How do you set layouts?

### ISSUE THREAD

**Issue by tsurantino** [donpark/hbs#98]
Hi all,

I installed `hbs` through `express-generator`. One thing that they do is add two view files: `layout.hbs` and `index.hbs` which seems to suggest there is a layout behaviour included with this package.

I am looking to find out where defaults for layouts are set and how they can be overridden. I was not able to find anything explicitly clear in the source files.

Thanks for any help you can provide!

**Comment by dpolivy** [comment]
If you want to use a global layout for all responses, then you can set `res.locals.layout = 'layout';` in one of your express handlers. Or, to set it per route, just add a `layout` property to the context object. Include the name of the layout template without the extension.

**Comment by tsurantino** [comment]
That's awesome. I ended up finding the line in the module where the layout was loaded when rendered. Thanks for your response!

**Comment by awebdeveloper** [comment]
i am new to hbs.... could some one help me how do i set layout
